# model
ckpt_dir: ./ckpts
# vae
height_division_factor: 16
width_division_factor: 16
time_division_factor: 4
time_division_remainder: 1

cpu_offload: False
use_sp: False
sp_size: 1
trainable_models: "q_loras,k_loras,v_loras,o_loras"
# data

# optimizer

# train

# log & eval
